resources:
- name: paas-docker-cloudfoundry-tools
  type: git
  source:
    uri: https://github.com/alphagov/paas-docker-cloudfoundry-tools.git
    branch: master

- name: paas-tech-docs
  type: git
  source:
    uri: https://github.com/alphagov/paas-tech-docs.git
    branch: master

- name: paas-semver-resource
  type: git
  source:
    uri: https://github.com/alphagov/paas-semver-resource.git
    branch: gds_master

- name: psql
  type: registry-image
  source: &build-image-source
    username: ((dockerhub_username))
    password: ((dockerhub_password))
    repository: ((dockerhub_username))/psql

- name: spruce
  type: registry-image
  source:
    <<: *build-image-source
    repository: ((dockerhub_username))/spruce

- name: json-minify
  type: registry-image
  source:
    <<: *build-image-source
    repository: ((dockerhub_username))/json-minify

- name: terraform
  type: registry-image
  source:
    <<: *build-image-source
    repository: ((dockerhub_username))/terraform

- name: self-update-pipelines
  type: registry-image
  source:
    <<: *build-image-source
    repository: ((dockerhub_username))/self-update-pipelines

- name: git-ssh
  type: registry-image
  source:
    <<: *build-image-source
    repository: ((dockerhub_username))/git-ssh

- name: curl-ssl
  type: registry-image
  source:
    <<: *build-image-source
    repository: ((dockerhub_username))/curl-ssl

- name: cf-cli
  type: registry-image
  source:
    <<: *build-image-source
    repository: ((dockerhub_username))/cf-cli

- name: cf-acceptance-tests
  type: registry-image
  source:
    <<: *build-image-source
    repository: ((dockerhub_username))/cf-acceptance-tests

- name: cf-uaac
  type: registry-image
  source:
    <<: *build-image-source
    repository: ((dockerhub_username))/cf-uaac

- name: certstrap
  type: registry-image
  source:
    <<: *build-image-source
    repository: ((dockerhub_username))/certstrap

- name: bosh-shell
  type: registry-image
  source:
    <<: *build-image-source
    repository: ((dockerhub_username))/bosh-shell

- name: bosh
  type: registry-image
  source:
    <<: *build-image-source
    repository: ((dockerhub_username))/bosh

- name: bosh-cli-v2
  type: registry-image
  source:
    <<: *build-image-source
    repository: ((dockerhub_username))/bosh-cli-v2

- name: awscli
  type: registry-image
  source:
    <<: *build-image-source
    repository: ((dockerhub_username))/awscli

- name: tech-docs
  type: registry-image
  source:
    <<: *build-image-source
    repository: ((dockerhub_username))/tech-docs

- name: semver-resource
  type: registry-image
  source:
    <<: *build-image-source
    repository: ((dockerhub_username))/semver-resource

jobs:
- name: build-psql
  plan:
  - get: paas-docker-cloudfoundry-tools
  - task: build
    privileged: true
    config: &build-image-config
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/psql
      inputs:
      - name: paas-docker-cloudfoundry-tools
      outputs:
      - name: image
      run:
        path: build
  - task: create-image-tag
    config: &create-image-tag
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: image
      outputs:
      - name: image
      run:
        path: sh
        args:
          - -e
          - -u
          - -c
          - |
            cut -d : -f 2 image/digest > image/tag
  - put: psql
    params:
      image: image/image.tar
      additional_tags: image/tag

- name: build-spruce
  plan:
  - get: paas-docker-cloudfoundry-tools
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/spruce
  - task: create-image-tag
    config: *create-image-tag
  - put: spruce
    params:
      image: image/image.tar
      additional_tags: image/tag

- name: build-json-minify
  plan:
  - get: paas-docker-cloudfoundry-tools
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/json-minify
  - task: create-image-tag
    config: *create-image-tag
  - put: json-minify
    params:
      image: image/image.tar
      additional_tags: image/tag

- name: build-terraform
  plan:
  - get: paas-docker-cloudfoundry-tools
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/terraform
  - task: create-image-tag
    config: *create-image-tag
  - put: terraform
    params:
      image: image/image.tar
      additional_tags: image/tag

- name: build-self-update-pipelines
  plan:
  - get: paas-docker-cloudfoundry-tools
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/self-update-pipelines
  - task: create-image-tag
    config: *create-image-tag
  - put: self-update-pipelines
    params:
      image: image/image.tar
      additional_tags: image/tag

- name: build-git-ssh
  plan:
  - get: paas-docker-cloudfoundry-tools
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/git-ssh
  - task: create-image-tag
    config: *create-image-tag
  - put: git-ssh
    params:
      image: image/image.tar
      additional_tags: image/tag

- name: build-curl-ssl
  plan:
  - get: paas-docker-cloudfoundry-tools
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/curl-ssl
  - task: create-image-tag
    config: *create-image-tag
  - put: curl-ssl
    params:
      image: image/image.tar
      additional_tags: image/tag

- name: build-cf-cli
  plan:
  - get: paas-docker-cloudfoundry-tools
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/cf-cli
  - task: create-image-tag
    config: *create-image-tag
  - put: cf-cli
    params:
      image: image/image.tar
      additional_tags: image/tag

- name: build-cf-acceptance-tests
  plan:
  - get: paas-docker-cloudfoundry-tools
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/cf-acceptance-tests
  - task: create-image-tag
    config: *create-image-tag
  - put: cf-acceptance-tests
    params:
      image: image/image.tar
      additional_tags: image/tag

- name: build-cf-uaac
  plan:
  - get: paas-docker-cloudfoundry-tools
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/cf-uaac
  - task: create-image-tag
    config: *create-image-tag
  - put: cf-uaac
    params:
      image: image/image.tar
      additional_tags: image/tag

- name: build-certstrap
  plan:
  - get: paas-docker-cloudfoundry-tools
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/certstrap
  - task: create-image-tag
    config: *create-image-tag
  - put: certstrap
    params:
      image: image/image.tar
      additional_tags: image/tag

- name: build-bosh-shell
  plan:
  - get: paas-docker-cloudfoundry-tools
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/bosh-shell
  - task: create-image-tag
    config: *create-image-tag
  - put: bosh-shell
    params:
      image: image/image.tar
      additional_tags: image/tag

- name: build-bosh
  plan:
  - get: paas-docker-cloudfoundry-tools
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/bosh
  - task: create-image-tag
    config: *create-image-tag
  - put: bosh
    params:
      image: image/image.tar
      additional_tags: image/tag

- name: build-bosh-cli-v2
  plan:
  - get: paas-docker-cloudfoundry-tools
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/bosh-cli-v2
  - task: create-image-tag
    config: *create-image-tag
  - put: bosh-cli-v2
    params:
      image: image/image.tar
      additional_tags: image/tag

- name: build-awscli
  plan:
  - get: paas-docker-cloudfoundry-tools
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/awscli
  - task: create-image-tag
    config: *create-image-tag
  - put: awscli
    params:
      image: image/image.tar
      additional_tags: image/tag

- name: build-paas-tech-docs
  plan:
  - get: paas-tech-docs
  - task: build
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: paas-tech-docs
        path: .
      outputs:
      - name: image
      run:
        path: build
  - put: tech-docs
    params:
      image: image/image.tar

- name: build-paas-semver-resource
  plan:
  - get: paas-semver-resource
  - task: build
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: paas-semver-resource
        path: .
      outputs:
      - name: image
      run:
        path: build
  - put: semver-resource
    params:
      image: image/image.tar
