resources:
  - name: paas-tech-docs
    type: git
    source:
      uri: https://github.com/alphagov/paas-tech-docs.git
      branch: main

  - name: paas-semver-resource
    type: git
    source:
      uri: https://github.com/alphagov/paas-semver-resource.git
      branch: gds_main

  - name: paas-grafana-annotation-resource
    type: git
    source:
      uri: https://github.com/alphagov/paas-grafana-annotation-resource.git
      branch: main

  - name: s3-resource-src
    type: git
    source:
      uri: https://github.com/alphagov/paas-s3-resource.git
      branch: gds_main

  - name: paas-prometheus-exporter
    type: git
    source:
      uri: https://github.com/alphagov/paas-prometheus-exporter.git
      branch: main

  - name: slack-notification-resource
    type: git
    source:
      uri: https://github.com/cloudfoundry-community/slack-notification-resource.git
      branch: master

  - name: slack-notification-resource-github-registry
    type: registry-image
    icon: github
    source: &build-image-source-github-registry
      username: ((github_username))
      password: ((github_registry_access_token))
      repository: ghcr.io/alphagov/paas/slack-notification-resource

  - name: tech-docs-docker-registry
    type: registry-image
    icon: docker
    source: &build-image-source-docker-registry
      username: ((dockerhub_username))
      password: ((dockerhub_password))
      repository: governmentpaas/tech-docs

  - name: tech-docs-github-registry
    type: registry-image
    icon: github
    source:
      <<: *build-image-source-github-registry
      repository: ghcr.io/alphagov/paas/tech-docs

  - name: semver-resource-docker-registry
    type: registry-image
    icon: docker
    source:
      <<: *build-image-source-docker-registry
      repository: governmentpaas/semver-resource

  - name: semver-resource-github-registry
    type: registry-image
    icon: github
    source:
      <<: *build-image-source-github-registry
      repository: ghcr.io/alphagov/paas/semver-resource

  - name: grafana-annotation-resource-docker-registry
    type: registry-image
    icon: docker
    source:
      <<: *build-image-source-docker-registry
      repository: governmentpaas/grafana-annotation-resource

  - name: grafana-annotation-resource-github-registry
    type: registry-image
    icon: github
    source:
      <<: *build-image-source-github-registry
      repository: ghcr.io/alphagov/paas/grafana-annotation-resource

  - name: s3-resource-github-registry
    type: registry-image
    icon: github
    source:
      <<: *build-image-source-github-registry
      repository: ghcr.io/alphagov/paas/s3-resource

  - name: paas-prometheus-exporter-docker-registry
    type: registry-image
    icon: docker
    source:
      <<: *build-image-source-docker-registry
      repository: governmentpaas/paas-prometheus-exporter

  - name: paas-prometheus-exporter-github-registry
    type: registry-image
    icon: github
    source:
      <<: *build-image-source-github-registry
      repository: ghcr.io/alphagov/paas/paas-prometheus-exporter

jobs:
  - name: build-paas-tech-docs
    plan:
      - get: paas-tech-docs
        trigger: true
      - task: build
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ghcr.io/alphagov/paas/concourse-oci-build-task
              tag: e7469f93077d814b34ecca70b98848d9717b4e02ca6e21247164ab1defa1201a
          inputs:
            - name: paas-tech-docs
              path: .
          outputs:
            - name: image
          run:
            path: build
      - task: create-image-tag
        config: &create-image-tag
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ghcr.io/alphagov/paas/concourse-oci-build-task
              tag: e7469f93077d814b34ecca70b98848d9717b4e02ca6e21247164ab1defa1201a
          inputs:
            - name: paas-tech-docs
            - name: image
          outputs:
            - name: image
          run:
            path: sh
            args:
              - -e
              - -u
              - -c
              - |
                git_branch_name="$(cd paas-tech-docs && \
                              git rev-parse --abbrev-ref HEAD | sed -e 's/^/ /')"

                git_commit_sha="$(cd paas-tech-docs && \
                         git log --pretty=format:'%H' -n 1)"

                echo "${git_branch_name} ${git_commit_sha} latest HEAD main" > image/tags
      - put: tech-docs-docker-registry
        params:
          image: image/image.tar
          additional_tags: image/tags

      - put: tech-docs-github-registry
        params:
          image: image/image.tar
          additional_tags: image/tags

  - name: build-paas-semver-resource
    plan:
      - get: paas-semver-resource
        trigger: true
      - task: build
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ghcr.io/alphagov/paas/concourse-oci-build-task
              tag: e7469f93077d814b34ecca70b98848d9717b4e02ca6e21247164ab1defa1201a
          inputs:
            - name: paas-semver-resource
              path: .
          outputs:
            - name: image
          run:
            path: build
      - task: create-image-tag
        config: &create-image-tag
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ghcr.io/alphagov/paas/concourse-oci-build-task
              tag: e7469f93077d814b34ecca70b98848d9717b4e02ca6e21247164ab1defa1201a
          inputs:
            - name: paas-semver-resource
            - name: image
          outputs:
            - name: image
          run:
            path: sh
            args:
              - -e
              - -u
              - -c
              - |
                git_branch_name="$(cd paas-semver-resource && \
                              git rev-parse --abbrev-ref HEAD | sed -e 's/^/ /')"

                git_commit_sha="$(cd paas-semver-resource && \
                         git log --pretty=format:'%H' -n 1)"

                echo "${git_branch_name} ${git_commit_sha} latest HEAD main" > image/tags
      - put: semver-resource-docker-registry
        params:
          image: image/image.tar
          additional_tags: image/tags
      - put: semver-resource-github-registry
        params:
          image: image/image.tar
          additional_tags: image/tags

  - name: build-paas-prometheus-exporter
    plan:
      - get: paas-prometheus-exporter
        trigger: true
      - task: build
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ghcr.io/alphagov/paas/concourse-oci-build-task
              tag: e7469f93077d814b34ecca70b98848d9717b4e02ca6e21247164ab1defa1201a
          inputs:
            - name: paas-prometheus-exporter
              path: .
          outputs:
            - name: image
          run:
            path: build
      - task: create-image-tag
        config: &create-image-tag
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ghcr.io/alphagov/paas/concourse-oci-build-task
              tag: e7469f93077d814b34ecca70b98848d9717b4e02ca6e21247164ab1defa1201a
          inputs:
            - name: paas-prometheus-exporter
            - name: image
          outputs:
            - name: image
          run:
            path: sh
            args:
              - -e
              - -u
              - -c
              - |
                git_branch_name="$(cd paas-prometheus-exporter && \
                              git rev-parse --abbrev-ref HEAD | sed -e 's/^/ /')"

                git_commit_sha="$(cd paas-prometheus-exporter && \
                         git log --pretty=format:'%H' -n 1)"

                echo "${git_branch_name} ${git_commit_sha} latest HEAD main" > image/tags
      - put: paas-prometheus-exporter-docker-registry
        params:
          image: image/image.tar
          additional_tags: image/tags

      - put: paas-prometheus-exporter-github-registry
        params:
          image: image/image.tar
          additional_tags: image/tags

  - name: build-paas-grafana-annotation-resource
    plan:
      - get: paas-grafana-annotation-resource
        trigger: true
      - task: build
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ghcr.io/alphagov/paas/concourse-oci-build-task
              tag: e7469f93077d814b34ecca70b98848d9717b4e02ca6e21247164ab1defa1201a
          inputs:
            - name: paas-grafana-annotation-resource
              path: .
          outputs:
            - name: image
          run:
            path: build
      - task: create-image-tag
        config: &create-image-tag
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ghcr.io/alphagov/paas/concourse-oci-build-task
              tag: e7469f93077d814b34ecca70b98848d9717b4e02ca6e21247164ab1defa1201a
          inputs:
            - name: paas-grafana-annotation-resource
            - name: image
          outputs:
            - name: image
          run:
            path: sh
            args:
              - -e
              - -u
              - -c
              - |
                git_branch_name="$(cd paas-grafana-annotation-resource && \
                              git rev-parse --abbrev-ref HEAD | sed -e 's/^/ /')"

                git_commit_sha="$(cd paas-grafana-annotation-resource && \
                         git log --pretty=format:'%H' -n 1)"

                echo "${git_branch_name} ${git_commit_sha} latest HEAD main" > image/tags
      - put: grafana-annotation-resource-docker-registry
        params:
          image: image/image.tar
          additional_tags: image/tags
      - put: grafana-annotation-resource-github-registry
        params:
          image: image/image.tar
          additional_tags: image/tags

  - name: build-s3-resource
    plan:
      - get: s3-resource-src
        trigger: true
      - task: build
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ghcr.io/alphagov/paas/concourse-oci-build-task
              tag: e7469f93077d814b34ecca70b98848d9717b4e02ca6e21247164ab1defa1201a
          inputs:
            - name: s3-resource-src
              path: .
          outputs:
            - name: image
          run:
            path: build
      - task: create-image-tag
        config: &create-image-tag
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ghcr.io/alphagov/paas/concourse-oci-build-task
              tag: e7469f93077d814b34ecca70b98848d9717b4e02ca6e21247164ab1defa1201a
          inputs:
            - name: s3-resource-src
            - name: image
          outputs:
            - name: image
          run:
            path: sh
            args:
              - -e
              - -u
              - -c
              - |
                git_branch_name="$(cd s3-resource-src && \
                              git rev-parse --abbrev-ref HEAD | sed -e 's/^/ /')"

                git_commit_sha="$(cd s3-resource-src && \
                          git log --pretty=format:'%H' -n 1)"

                echo "${git_branch_name} ${git_commit_sha} latest HEAD main" > image/tags
      - put: s3-resource-github-registry
        params:
          image: image/image.tar
          additional_tags: image/tags

  - name: build-slack-notification-resource
    plan:
      - get: slack-notification-resource
        trigger: true
      - task: build
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ghcr.io/alphagov/paas/concourse-oci-build-task
              tag: e7469f93077d814b34ecca70b98848d9717b4e02ca6e21247164ab1defa1201a
          inputs:
            - name: slack-notification-resource
              path: .
          outputs:
            - name: image
          run:
            path: build
      - task: create-image-tag
        config: &create-image-tag
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ghcr.io/alphagov/paas/concourse-oci-build-task
              tag: e7469f93077d814b34ecca70b98848d9717b4e02ca6e21247164ab1defa1201a
          inputs:
            - name: slack-notification-resource
            - name: image
          outputs:
            - name: image
          run:
            path: sh
            args:
              - -e
              - -u
              - -c
              - |
                git_branch_name="$(cd slack-notification-resource && \
                              git rev-parse --abbrev-ref HEAD | sed -e 's/^/ /')"

                git_commit_sha="$(cd slack-notification-resource && \
                         git log --pretty=format:'%H' -n 1)"

                echo "${git_branch_name} ${git_commit_sha} latest HEAD main" > image/tags
      - put: slack-notification-resource-github-registry
        params:
          image: image/image.tar
          additional_tags: image/tags
