resource_types:
- name: pull-request
  type: docker-image
  check_every: 24h
  source:
    # temporary until there is a version which contains the submodule param
    repository: ghcr.io/alphagov/paas/teliaoss-github-pr-resource
    tag: c41729d09b4da671765979933fd7e24388c34e05

resources:
- name: paas-tech-docs-pr
  type: pull-request
  check_every: 1m
  source:
    repository: alphagov/paas-tech-docs
    access_token: ((github_access_token))
    disable_forks: true

- name: paas-semver-resource-pr
  type: pull-request
  check_every: 1m
  source:
    repository: alphagov/paas-semver-resource
    access_token: ((github_access_token))
    disable_forks: true

- name: paas-grafana-annotation-resource-pr
  type: pull-request
  check_every: 1m
  source:
    repository: alphagov/paas-grafana-annotation-resource
    access_token: ((github_access_token))
    disable_forks: true

- name: paas-prometheus-exporter
  type: pull-request
  check_every: 1m
  source:
    repository: alphagov/paas-prometheus-exporter
    access_token: ((github_access_token))
    disable_forks: true

- name: tech-docs
  type: registry-image
  source: &build-image-source
    username: ((github_username))
    password: ((github_registry_access_token))
    tag: pr-build
    repository: ghcr.io/alphagov/paas/tech-docs

- name: semver-resource
  type: registry-image
  source:
    <<: *build-image-source
    repository: ghcr.io/alphagov/paas/semver-resource

- name: grafana-annotation-resource
  type: registry-image
  source:
    <<: *build-image-source
    repository: ghcr.io/alphagov/paas/grafana-annotation-resource

- name: paas-prometheus-exporter-resource
  type: registry-image
  icon: github
  source:
    <<: *build-image-source
    repository: ghcr.io/alphagov/paas/paas-prometheus-exporter

jobs:
- name: build-paas-tech-pr
  serial: true
  plan:
  - get: paas-tech-docs-pr
    version: every
    trigger: true
    params:
      integration_tool: checkout
      submodules: true
  - put: update-paas-tech-docs-pr
    resource: paas-tech-docs-pr
    params:
      path: paas-tech-docs-pr
      context: ((github_status_context))/build-paas-tech-pr
      status: PENDING
    get_params:
      skip_download: true
  - task: build
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ghcr.io/alphagov/paas/concourse-oci-build-task
          tag: e7469f93077d814b34ecca70b98848d9717b4e02ca6e21247164ab1defa1201a
      inputs:
      - name: paas-tech-docs-pr
        path: .
      outputs:
      - name: image
      run:
        path: build
  - task: create-image-tag
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ghcr.io/alphagov/paas/concourse-oci-build-task
          tag: e7469f93077d814b34ecca70b98848d9717b4e02ca6e21247164ab1defa1201a
      inputs:
      - name: paas-tech-docs-pr
      - name: image
      outputs:
      - name: image
      run:
        path: sh
        args:
          - -e
          - -u
          - -c
          - |
            cd paas-tech-docs-pr && git rev-parse --abbrev-ref HEAD > ../image/branch
    on_success:
      do:
        - put: tech-docs
          params:
            image: image/image.tar
            additional_tags: image/branch
        - put: paas-tech-docs-pr
          params:
            path: paas-tech-docs-pr
            context: ((github_status_context))/build-paas-tech-pr
            status: SUCCESS
          get_params:
            skip_download: true
    on_failure:
      put: paas-tech-docs-pr
      params:
        path: paas-tech-docs-pr
        context: ((github_status_context))/build-paas-tech-pr
        status: FAILURE
      get_params:
        skip_download: true

- name: build-paas-prometheus-exporter-pr
  plan:
    - get: paas-prometheus-exporter
      trigger: true
    - task: build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: ghcr.io/alphagov/paas/concourse-oci-build-task
            tag: e7469f93077d814b34ecca70b98848d9717b4e02ca6e21247164ab1defa1201a
        inputs:
          - name: paas-prometheus-exporter
            path: .
        outputs:
          - name: image
        run:
          path: build
    - task: create-image-tag
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: ghcr.io/alphagov/paas/concourse-oci-build-task
            tag: e7469f93077d814b34ecca70b98848d9717b4e02ca6e21247164ab1defa1201a
        inputs:
          - name: paas-prometheus-exporter
          - name: image
        outputs:
          - name: image
        run:
          path: sh
          args:
            - -e
            - -u
            - -c
            - |
              git_branch_name="$(cd paas-prometheus-exporter && \
                            git rev-parse --abbrev-ref HEAD | sed -e 's/^/ /')"

              git_commit_sha="$(cd paas-prometheus-exporter && \
                       git log --pretty=format:'%H' -n 1)"

              echo "${git_branch_name} ${git_commit_sha}" > image/tags
    - put: paas-prometheus-exporter-resource
      params:
        image: image/image.tar
        additional_tags: image/tags

- name: build-paas-semver-resource-pr
  serial: true
  plan:
  - get: paas-semver-resource-pr
    version: every
    trigger: true
    params:
      integration_tool: checkout
      submodules: true
  - put: update-paas-semver-resource-pr
    resource: paas-semver-resource-pr
    params:
      path: paas-semver-resource-pr
      context: ((github_status_context))/build-paas-semver-resource-pr
      status: PENDING
    get_params:
      skip_download: true
  - task: build
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ghcr.io/alphagov/paas/concourse-oci-build-task
          tag: e7469f93077d814b34ecca70b98848d9717b4e02ca6e21247164ab1defa1201a
      inputs:
      - name: paas-semver-resource-pr
        path: .
      outputs:
      - name: image
      run:
        path: build
  - task: create-image-tag
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ghcr.io/alphagov/paas/concourse-oci-build-task
          tag: e7469f93077d814b34ecca70b98848d9717b4e02ca6e21247164ab1defa1201a
      inputs:
      - name: paas-semver-resource-pr
      - name: image
      outputs:
      - name: image
      run:
        path: sh
        args:
          - -e
          - -u
          - -c
          - |
            cd paas-semver-resource-pr && git rev-parse --abbrev-ref HEAD > ../image/branch
    on_success:
      do:
        - put: semver-resource
          params:
            image: image/image.tar
            additional_tags: image/branch
        - put: paas-semver-resource-pr
          params:
            path: paas-semver-resource-pr
            context: ((github_status_context))/build-paas-semver-resource-pr
            status: SUCCESS
          get_params:
            skip_download: true
    on_failure:
      put: paas-semver-resource-pr
      params:
        path: paas-semver-resource-pr
        context: ((github_status_context))/build-paas-semver-resource-pr
        status: FAILURE
      get_params:
        skip_download: true

- name: build-paas-grafana-annotation-resource-pr
  serial: true
  plan:
  - get: paas-grafana-annotation-resource-pr
    version: every
    trigger: true
    params:
      integration_tool: checkout
      submodules: true
  - put: update-paas-grafana-annotation-resource-pr
    resource: paas-grafana-annotation-resource-pr
    params:
      path: paas-grafana-annotation-resource-pr
      context: ((github_status_context))/build-paas-grafana-annotation-resource-pr
      status: PENDING
    get_params:
      skip_download: true
  - task: build
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ghcr.io/alphagov/paas/concourse-oci-build-task
          tag: e7469f93077d814b34ecca70b98848d9717b4e02ca6e21247164ab1defa1201a
      inputs:
      - name: paas-grafana-annotation-resource-pr
        path: .
      outputs:
      - name: image
      run:
        path: build
  - task: create-image-tag
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ghcr.io/alphagov/paas/concourse-oci-build-task
          tag: e7469f93077d814b34ecca70b98848d9717b4e02ca6e21247164ab1defa1201a
      inputs:
      - name: paas-grafana-annotation-resource-pr
      - name: image
      outputs:
      - name: image
      run:
        path: sh
        args:
          - -e
          - -u
          - -c
          - |
            cd paas-grafana-annotation-resource-pr && git rev-parse --abbrev-ref HEAD > ../image/branch
    on_success:
      do:
        - put: grafana-annotation-resource
          params:
            image: image/image.tar
            additional_tags: image/branch
        - put: paas-grafana-annotation-resource-pr
          params:
            path: paas-grafana-annotation-resource-pr
            context: ((github_status_context))/build-paas-grafana-annotation-resource-pr
            status: SUCCESS
          get_params:
            skip_download: true
    on_failure:
      put: paas-grafana-annotation-resource-pr
      params:
        path: paas-grafana-annotation-resource-pr
        context: ((github_status_context))/build-paas-grafana-annotation-resource-pr
        status: FAILURE
      get_params:
        skip_download: true
