---

resource_types:
  - name: s3-iam
    type: docker-image
    check_every: 24h
    source:
      repository: ghcr.io/alphagov/paas/s3-resource
      tag: 97e441efbfb06ac7fb09786fd74c64b05f9cc907

  - name: slack-notification-resource
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: paas-team-manual
    type: git
    check_every: 1m
    source:
      uri: https://github.com/alphagov/paas-team-manual.git
      branch: main

  - name: ssh-private-key
    type: s3-iam
    check_every: 24h
    source:
      bucket: ((state_bucket))
      versioned_file: ci_build_tag_key
      region_name: ((aws_region))

  - name: slack-notification
    type: slack-notification-resource
    source:
      url: ((slack_webhook_url))

jobs:
  - name: publish
    serial: true
    plan:
      - get: paas-team-manual
        trigger: true
      - get: ssh-private-key
      - task: publish
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ruby
              tag: 2.7-slim
          inputs:
            - name: paas-team-manual
            - name: ssh-private-key
          params:
            DEPLOY_ENV: ((deploy_env))
            AWS_ACCOUNT: ((aws_account))
          run:
            path: sh
            args:
              - -e
              - -u
              - -c
              - |
                #apk add --no-progress --update build-base libffi-dev git
                apt-get update
                apt-get install -y build-essential libffi-dev git libcurl4-openssl-dev

                chmod 600 ssh-private-key/ci_build_tag_key
                mkdir -p /root/.ssh
                cp ssh-private-key/ci_build_tag_key /root/.ssh/id_rsa

                git config --global push.default simple
                git config --global user.email "paas-release-ci@${DEPLOY_ENV}.${AWS_ACCOUNT}"
                git config --global user.name "PaaS Release CI server ${DEPLOY_ENV} in ${AWS_ACCOUNT}"
                export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

                cd paas-team-manual

                new_remote="$(git remote -v | sed -n 's|origin.*https://\([^/]*\)/\([^ ]*\).*fetch.*|git@\1:\2|p')"
                git remote set-url origin "$new_remote"
                
                echo "Forcing it to use new bundler"
                gem update --system
                BUNDLER_VERSION="tail -1 Gemfile.lock | tr -d \" \""
                
                gem install bundler -v $BUNDLER_VERSION

                bundle install
                bundle exec rake publish
        on_failure:
          put: slack-notification
          params:
            text: "Job $BUILD_NAME in $BUILD_JOB_NAME on $BUILD_PIPELINE_NAME failed. Check the logs at $ATC_EXTERNAL_URL/builds/$BUILD_ID."
