---
resource_types:
  - name: s3-iam
    type: docker-image
    check_every: 24h
    source:
      repository: governmentpaas/s3-resource
      tag: fda60bf4c5f85e96c16f704e128e5ead9e84d30d

  - name: slack-notification-resource
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: paas-codimd
    type: git
    check_every: 1m
    source:
      uri: https://github.com/alphagov/paas-codimd
      branch: gds_master

  - name: slack-notification
    type: slack-notification-resource
    source:
      url: ((slack_webhook_url))

jobs:
  - name: deploy
    serial: true
    plan:
      - get: paas-codimd
        trigger: true

      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: 10
          inputs:
          - name: paas-codimd
          outputs:
          - name: paas-codimd
          run:
            path: sh
            args:
              - -e
              - -u
              - -c
              - |
                cd paas-codimd

                echo "Installing application dependencies..."
                npm install

                echo "Building application assets..."
                npm run build

      - task: push
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/cf-cli
              tag: latest
          inputs:
            - name: paas-codimd
          params:
            CF_API: https://api.((cf_system_domain))
            CF_USER: ((cf_user))
            CF_PASSWORD: ((cf_password))
            CF_APPS_DOMAIN: ((cf_apps_domain))
            CF_SYSTEM_DOMAIN: ((cf_system_domain))
            CF_ORG: govuk-paas
            CF_SPACE: tools
            HACKMD_GITHUB_CLIENT_ID: ((hackmd_github_client_id))
            HACKMD_GITHUB_CLIENT_SECRET: ((hackmd_github_client_secret))
            HACKMD_SESSION_SECRET: ((hackmd_session_secret))
          run:
            path: sh
            args:
              - -e
              - -u
              - -c
              - |
                echo "Logging on to CloudFoundry..."
                cf login \
                  -a "${CF_API}" \
                  -u "${CF_USER}" \
                  -p "${CF_PASSWORD}" \
                  -o "${CF_ORG}" \
                  -s "${CF_SPACE}"

                cf create-service postgres tiny-unencrypted-9.5 hackmd-db
                while ! cf service hackmd-db | grep -q 'create succeeded'; do
                  echo "Waiting for creation of service to complete..."
                  sleep 30
                done
                cf bind-service hackmd hackmd-db

                cf create-service aws-s3-bucket default hackmd-store -c '{"public_bucket":true}'
                while ! cf service hackmd-store | grep -q 'create succeeded'; do
                  echo "Waiting for creation of service to complete..."
                  sleep 5
                done
                cf bind-service hackmd hackmd-store -c '{"permissions": "read-write"}'

                echo "Generating manifest variables"
                cat <<EOF > paas-codimd/vars.yml
                ---
                domain: ${CF_APPS_DOMAIN}
                github_client_id: ${HACKMD_GITHUB_CLIENT_ID}
                github_client_secret: ${HACKMD_GITHUB_CLIENT_SECRET}
                secret: ${HACKMD_SESSION_SECRET}
                EOF

                cd paas-codimd
                cf push hackmd --vars-file vars.yml

        on_failure:
          put: slack-notification
          params:
            text: "Job $BUILD_NAME in $BUILD_JOB_NAME on $BUILD_PIPELINE_NAME failed. Check the logs at $ATC_EXTERNAL_URL/builds/$BUILD_ID."
