---
resource_types:
  - name: slack-notification-resource
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: paas-product-pages
    type: git
    check_every: 1m
    source:
      uri: https://github.com/alphagov/paas-product-pages.git
      branch: main

  - name: slack-notification
    type: slack-notification-resource
    source:
      url: ((slack_webhook_url))

jobs:
  - name: deploy
    serial: true

    on_failure:
      put: slack-notification
      params:
        text: "Job $BUILD_NAME in $BUILD_JOB_NAME on $BUILD_PIPELINE_NAME failed. Check the logs at $ATC_EXTERNAL_URL/builds/$BUILD_ID."

    plan:
      - get: paas-product-pages
        trigger: true

      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: lts
          inputs:
            - name: paas-product-pages
          outputs:
            - name: paas-product-pages
          run:
            dir: paas-product-pages
            path: sh
            args:
              - -e
              - -u
              - -c
              - |
                npm install
                npx rollup -c && npx next build && npx next export

      - task: push
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ghcr.io/alphagov/paas/cf-cli
              tag: 90f9f534ed5a3887b9c5d55a20cca6561f7de6a4
          inputs:
            - name: paas-product-pages
          params:
            CF_API: https://api.((cf_system_domain))
            CF_USER: ((cf_user))
            CF_PASSWORD: ((cf_password))
            CF_APPS_DOMAIN: ((cf_apps_domain))
            CF_SYSTEM_DOMAIN: ((cf_system_domain))
            CF_ORG: govuk-paas
            CF_SPACE: docs
          run:
            dir: paas-product-pages
            path: sh
            args:
              - -e
              - -u
              - -c
              - |
                echo "Logging on to Cloudfoundry..."
                cf login \
                  -a "${CF_API}" \
                  -u "${CF_USER}" \
                  -p "${CF_PASSWORD}" \
                  -o "${CF_ORG}" \
                  -s "${CF_SPACE}"

                cf cancel-deployment paas-product-pages || true
                cf push paas-product-pages --strategy=rolling

                cf map-route paas-product-pages \
                  --hostname www "${CF_SYSTEM_DOMAIN}"

                cd redirect
                cf cancel-deployment paas-product-pages-redirect || true
                cf push paas-product-pages-redirect --strategy=rolling
