---
resource_types:
  - name: slack-notification-resource
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: paas-rubbernecker
    type: git
    check_every: 1m
    source:
      uri: https://github.com/alphagov/paas-rubbernecker.git
      branch: main

  - name: slack-notification
    type: slack-notification-resource
    source:
      url: ((slack_webhook_url))

jobs:
  - name: test
    plan:
      - get: paas-rubbernecker
        trigger: true

      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: golang
              tag: "1.20"
          inputs:
            - name: paas-rubbernecker
          run:
            path: sh
            args:
              - -e
              - -u
              - -c
              - |
                cd paas-rubbernecker
                make test
        on_failure: &slack_failure_notification
          put: slack-notification
          params:
            text: "Job $BUILD_NAME in $BUILD_JOB_NAME on $BUILD_PIPELINE_NAME failed. Check the logs at $ATC_EXTERNAL_URL/builds/$BUILD_ID."

  - name: deploy
    serial: true
    plan:
      - get: paas-rubbernecker
        passed: [test]
        trigger: true

      - task: push
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ghcr.io/alphagov/paas/cf-cli
              tag: d233a6d5064fc720fb90fdb1c1e773ac21f3857c
          inputs:
            - name: paas-rubbernecker
          params:
            CF_API: https://api.((cf_system_domain))
            CF_LONDON_API: https://api.london.((cf_system_domain))
            CF_USER: ((cf_user))
            CF_PASSWORD: ((cf_password))
            CF_LONDON_USER: ((cf_london_user))
            CF_LONDON_PASSWORD: ((cf_london_password))
            CF_ORG: govuk-paas
            CF_SPACE: tools
            PIVOTAL_TRACKER_PROJECT_ID: ((pivotal_tracker_project_id))
            PIVOTAL_TRACKER_API_TOKEN: ((pivotal_tracker_api_token))
            PAGERDUTY_AUTHTOKEN: ((pagerduty_authtoken))
          run:
            path: sh
            args:
              - -e
              - -u
              - -c
              - |
                cd paas-rubbernecker

                echo "Logging on to Cloudfoundry..."
                cf login \
                  -a "${CF_API}" \
                  -u "${CF_USER}" \
                  -p "${CF_PASSWORD}" \
                  -o "${CF_ORG}" \
                  -s "${CF_SPACE}"

                echo "Deploying Rubbernecker redirect to Ireland..."
                cd redirect
                cf push paas-rubbernecker-redirect -f manifest.yml --strategy rolling
                cf logout
                cd ..
                
                echo "Logging on to CloudFoundry London..."
                cf login \
                  -a "${CF_LONDON_API}" \
                  -u "${CF_LONDON_USER}" \
                  -p "${CF_LONDON_PASSWORD}" \
                  -o "${CF_ORG}" \
                  -s "${CF_SPACE}"

                echo "Generating manifest"
                cat <<EOF > manifest.yml
                ---
                applications:
                - name: rubbernecker
                  memory: 128M
                  stack: cflinuxfs3
                  instances: 1
                  buildpack: go_buildpack
                  env:
                    PIVOTAL_TRACKER_PROJECT_ID: "${PIVOTAL_TRACKER_PROJECT_ID}"
                    PIVOTAL_TRACKER_API_TOKEN: "${PIVOTAL_TRACKER_API_TOKEN}"
                    PAGERDUTY_AUTHTOKEN: "${PAGERDUTY_AUTHTOKEN}"
                    GOPACKAGENAME: github.com/alphagov/paas-rubbernecker
                    GOVERSION: go1.20
                EOF

                cf push rubbernecker -f manifest.yml --strategy rolling
        on_failure: *slack_failure_notification
