---
resource_types:
  - name: s3-iam
    type: docker-image
    check_every: 24h
    source:
      repository: ghcr.io/alphagov/paas/s3-resource
      tag: fda60bf4c5f85e96c16f704e128e5ead9e84d30d

  - name: slack-notification-resource
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: paas-rubbernecker
    type: git
    check_every: 1m
    source:
      uri: https://github.com/alphagov/paas-rubbernecker.git
      branch: master

  - name: slack-notification
    type: slack-notification-resource
    source:
      url: ((slack_webhook_url))

jobs:
  - name: test
    plan:
      - get: paas-rubbernecker
        trigger: true

      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: golang
              tag: 1.12
          inputs:
            - name: paas-rubbernecker
          run:
            path: sh
            args:
              - -e
              - -u
              - -c
              - |
                cd paas-rubbernecker
                make test
        on_failure: &slack_failure_notification
          put: slack-notification
          params:
            text: "Job $BUILD_NAME in $BUILD_JOB_NAME on $BUILD_PIPELINE_NAME failed. Check the logs at $ATC_EXTERNAL_URL/builds/$BUILD_ID."

  - name: deploy
    serial: true
    plan:
      - get: paas-rubbernecker
        passed: [test]
        trigger: true

      - task: push
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ghcr.io/alphagov/paas/cf-cli
              tag: 90f9f534ed5a3887b9c5d55a20cca6561f7de6a4
          inputs:
            - name: paas-rubbernecker
          params:
            CF_API: https://api.((cf_system_domain))
            CF_USER: ((cf_user))
            CF_PASSWORD: ((cf_password))
            CF_ORG: govuk-paas
            CF_SPACE: tools
            CF_APPS_DOMAIN: ((cf_apps_domain))
            CF_SYSTEM_DOMAIN: ((cf_system_domain))
            PIVOTAL_TRACKER_PROJECT_ID: ((pivotal_tracker_project_id))
            PIVOTAL_TRACKER_API_TOKEN: ((pivotal_tracker_api_token))
            PAGERDUTY_AUTHTOKEN: ((pagerduty_authtoken))
          run:
            path: sh
            args:
              - -e
              - -u
              - -c
              - |
                cd paas-rubbernecker

                echo "Logging on to Cloudfoundry..."
                cf login \
                  -a "${CF_API}" \
                  -u "${CF_USER}" \
                  -p "${CF_PASSWORD}" \
                  -o "${CF_ORG}" \
                  -s "${CF_SPACE}"

                echo "Generating manifest"
                cat <<EOF > manifest.yml
                ---
                applications:
                - name: rubbernecker
                  memory: 128M
                  stack: cflinuxfs3
                  instances: 1
                  buildpack: go_buildpack
                  env:
                    PIVOTAL_TRACKER_PROJECT_ID: "${PIVOTAL_TRACKER_PROJECT_ID}"
                    PIVOTAL_TRACKER_API_TOKEN: "${PIVOTAL_TRACKER_API_TOKEN}"
                    PAGERDUTY_AUTHTOKEN: "${PAGERDUTY_AUTHTOKEN}"
                    GO111MODULE: on
                    GOPACKAGENAME: github.com/alphagov/paas-rubbernecker
                    GOVERSION: go1.14
                EOF

                cf zero-downtime-push rubbernecker -f manifest.yml
        on_failure: *slack_failure_notification
