---
resource_types:
  - name: s3-iam
    type: docker-image
    source:
      repository: governmentpaas/s3-resource

  - name: semver-iam
    type: docker-image
    source:
      repository: governmentpaas/semver-resource

resources:
  - name: pipeline-trigger
    type: semver-iam
    source:
      bucket: {{state_bucket_name}}
      region_name: {{aws_region}}
      key: {{pipeline_trigger_file}}

  - name: paas-release-ci
    type: git
    source:
      uri: https://github.com/alphagov/paas-release-ci
      branch: {{branch_name}}

  - name: release-ci-tfstate
    type: s3-iam
    source:
      bucket: {{state_bucket_name}}
      region_name: {{aws_region}}
      versioned_file: release-ci.tfstate

jobs:
  - name: init
    plan:
      - put: pipeline-trigger
        params: {bump: patch}

  - name: terraform-destroy
    plan:
      - aggregate:
          - get: pipeline-trigger
            passed: ['init']
            trigger: true
          - get: paas-release-ci
          - get: release-ci-tfstate
      - task: terraform-destroy
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/terraform
          inputs:
            - name: paas-release-ci
            - name: release-ci-tfstate
          outputs:
            - name: updated-release-ci-tfstate
          params:
            TF_VAR_deploy_env: {{deploy_env}}
            TF_VAR_releases_bucket_name: {{releases_bucket_name}}
          run:
            path: sh
            args:
              - -e
              - -u
              - -c
              - |
                terraform destroy -force \
                  -state=release-ci-tfstate/release-ci.tfstate -state-out=updated-release-ci-tfstate/release-ci.tfstate \
                  paas-release-ci/terraform
        ensure:
          put: release-ci-tfstate
          params:
            file: updated-release-ci-tfstate/release-ci.tfstate
