---

resource_types:
- name: git-branches
  type: docker-image
  source:
    repository: cfcommunity/git-branches-resource

- name: semver-iam
  type: docker-image
  source:
    repository: governmentpaas/semver-resource

resources:
- name: concourse-branch-manager
  type: git
  source:
    uri: https://github.com/alphagov/paas-concourse-branch-manager.git
    branch: 115142265_do_not_verify
    ignore_paths: [Gemfile, Gemfile.lock]

- name: git-branches
  type: git-branches
  source:
    uri: https://github.com/alphagov/paas-example-boshrelease.git
    branch_regexp: ".*"
    max_branches: 20

- name: template-repo
  type: git
  source:
    uri: https://github.com/alphagov/paas-release-ci.git
    branch: 115142265_initial_pipeline
    path: [templates/*]

- name: config-repo
  type: git
  source:
    uri: https://github.com/alphagov/paas-release-ci.git
    branch: 115142265_initial_pipeline

- name: credentials-repo
  type: git
  source:
    uri: https://github.com/alphagov/paas-release-ci.git
    branch: 115142265_initial_pipeline

- name: paas-example-boshrelease
  type: git-branches
  source:
    uri: https://github.com/alphagov/paas-example-boshrelease.git


jobs:
  - name: branch-manager
    serial: true
    plan:
    - get: concourse-branch-manager
      params: {depth: 20}
      trigger: true
    - get: git-branches
      trigger: true
    - get: template-repo
      params: {depth: 20}
      trigger: true
    - get: config-repo
      params: {depth: 20}
    - get: credentials-repo
      params: {depth: 20}
      trigger: true
    - task: manage-branches
      file: concourse-branch-manager/tasks/manage-branches.yml
      params:
        BRANCH_RESOURCE_TEMPLATE: template-repo/templates/resources-template.yml.erb
        BRANCH_RESOURCE_TYPES_TEMPLATE: template-repo/templates/resource_types-template.yml.erb
        BRANCH_JOB_TEMPLATE: template-repo/templates/job-template.yml.erb
        PIPELINE_COMMON_RESOURCES_TEMPLATE: template-repo/templates/common-resources-template.yml.erb
        CONCOURSE_URL: {{CONCOURSE_URL}}
        CONCOURSE_USERNAME: {{CONCOURSE_USERNAME}}
        CONCOURSE_PASSWORD: {{CONCOURSE_PASSWORD}}
        PIPELINE_NAME: paas-example-boshrelease
        GROUP_PER_BRANCH: true
